using System.Collections.Generic;

namespace PoESplit.ExileKit
{
	// Autogenerated by ExileKit
	static class BakedData
	{
		public static List<MapConnection>[] fConnections = new List<MapConnection>[]
		{
			new List<MapConnection>()
			{
				new MapConnection() { X1 = 264, Y1 = 405, X2 = 244, Y2 = 486 },
				new MapConnection() { X1 = 264, Y1 = 405, X2 = 285, Y2 = 346 },
				new MapConnection() { X1 = 285, Y1 = 346, X2 = 325, Y2 = 375 },
				new MapConnection() { X1 = 285, Y1 = 346, X2 = 314, Y2 = 300 },
				new MapConnection() { X1 = 314, Y1 = 300, X2 = 283, Y2 = 231 },
				new MapConnection() { X1 = 314, Y1 = 300, X2 = 371, Y2 = 247 },
				new MapConnection() { X1 = 371, Y1 = 247, X2 = 426, Y2 = 279 },
				new MapConnection() { X1 = 371, Y1 = 247, X2 = 419, Y2 = 211 },
				new MapConnection() { X1 = 419, Y1 = 211, X2 = 324, Y2 = 161 },
				new MapConnection() { X1 = 324, Y1 = 161, X2 = 305, Y2 = 68 },
				new MapConnection() { X1 = 305, Y1 = 68, X2 = 385, Y2 = 68 },
				new MapConnection() { X1 = 385, Y1 = 68, X2 = 480, Y2 = 158 },
				new MapConnection() { X1 = 385, Y1 = 68, X2 = 365, Y2 = -25 },
				new MapConnection() { X1 = 480, Y1 = 158, X2 = 470, Y2 = 107 },
				new MapConnection() { X1 = 480, Y1 = 158, X2 = 626, Y2 = 117 },
				new MapConnection() { X1 = 626, Y1 = 117, X2 = 580, Y2 = -25 },
			},
			new List<MapConnection>()
			{
				new MapConnection() { X1 = 528, Y1 = 313, X2 = 574, Y2 = 400 },
				new MapConnection() { X1 = 528, Y1 = 313, X2 = 574, Y2 = 267 },
				new MapConnection() { X1 = 528, Y1 = 313, X2 = 411, Y2 = 340 },
				new MapConnection() { X1 = 574, Y1 = 267, X2 = 530, Y2 = 218 },
				new MapConnection() { X1 = 574, Y1 = 267, X2 = 615, Y2 = 196 },
				new MapConnection() { X1 = 615, Y1 = 196, X2 = 540, Y2 = 122 },
				new MapConnection() { X1 = 615, Y1 = 196, X2 = 641, Y2 = 121 },
				new MapConnection() { X1 = 615, Y1 = 196, X2 = 680, Y2 = 265 },
				new MapConnection() { X1 = 745, Y1 = 275, X2 = 680, Y2 = 265 },
				new MapConnection() { X1 = 411, Y1 = 340, X2 = 221, Y2 = 288 },
				new MapConnection() { X1 = 411, Y1 = 340, X2 = 355, Y2 = 270 },
				new MapConnection() { X1 = 259, Y1 = 183, X2 = 196, Y2 = 215 },
				new MapConnection() { X1 = 259, Y1 = 183, X2 = 144, Y2 = 91 },
				new MapConnection() { X1 = 221, Y1 = 288, X2 = 248, Y2 = 334 },
				new MapConnection() { X1 = 318, Y1 = 220, X2 = 259, Y2 = 183 },
				new MapConnection() { X1 = 355, Y1 = 270, X2 = 318, Y2 = 220 },
			},
			new List<MapConnection>()
			{
				new MapConnection() { X1 = 461, Y1 = 369, X2 = 662, Y2 = 381 },
				new MapConnection() { X1 = 461, Y1 = 369, X2 = 652, Y2 = 309 },
				new MapConnection() { X1 = 652, Y1 = 309, X2 = 714, Y2 = 309 },
				new MapConnection() { X1 = 652, Y1 = 309, X2 = 616, Y2 = 252 },
				new MapConnection() { X1 = 589, Y1 = 185, X2 = 652, Y2 = 168 },
				new MapConnection() { X1 = 589, Y1 = 185, X2 = 478, Y2 = 140 },
				new MapConnection() { X1 = 478, Y1 = 140, X2 = 556, Y2 = 97 },
				new MapConnection() { X1 = 478, Y1 = 140, X2 = 394, Y2 = 118 },
				new MapConnection() { X1 = 478, Y1 = 140, X2 = 295, Y2 = 178 },
				new MapConnection() { X1 = 556, Y1 = 97, X2 = 503, Y2 = 61 },
				new MapConnection() { X1 = 616, Y1 = 252, X2 = 589, Y2 = 185 },
				new MapConnection() { X1 = 616, Y1 = 252, X2 = 295, Y2 = 178 },
				new MapConnection() { X1 = 295, Y1 = 178, X2 = 188, Y2 = 169 },
				new MapConnection() { X1 = 295, Y1 = 178, X2 = 262, Y2 = 129 },
				new MapConnection() { X1 = 262, Y1 = 129, X2 = 217, Y2 = 98 },
				new MapConnection() { X1 = 262, Y1 = 129, X2 = 285, Y2 = 76 },
			},
			new List<MapConnection>()
			{
				new MapConnection() { X1 = 610, Y1 = 370, X2 = 315, Y2 = 518 },
				new MapConnection() { X1 = 610, Y1 = 370, X2 = 555, Y2 = 275 },
				new MapConnection() { X1 = 610, Y1 = 370, X2 = 729, Y2 = 154 },
				new MapConnection() { X1 = 749, Y1 = 477, X2 = 610, Y2 = 370 },
				new MapConnection() { X1 = 555, Y1 = 275, X2 = 474, Y2 = 236 },
				new MapConnection() { X1 = 474, Y1 = 236, X2 = 292, Y2 = 344 },
				new MapConnection() { X1 = 474, Y1 = 236, X2 = 534, Y2 = 144 },
				new MapConnection() { X1 = 474, Y1 = 236, X2 = 372, Y2 = 194 },
				new MapConnection() { X1 = 292, Y1 = 344, X2 = 196, Y2 = 289 },
				new MapConnection() { X1 = 534, Y1 = 144, X2 = 464, Y2 = 90 },
				new MapConnection() { X1 = 372, Y1 = 194, X2 = 280, Y2 = 144 },
			},
			new List<MapConnection>()
			{
				new MapConnection() { X1 = 164, Y1 = 285, X2 = 230, Y2 = 350 },
				new MapConnection() { X1 = 75, Y1 = 298, X2 = 164, Y2 = 285 },
				new MapConnection() { X1 = 230, Y1 = 350, X2 = 406, Y2 = 224 },
				new MapConnection() { X1 = 406, Y1 = 224, X2 = 720, Y2 = 440 },
				new MapConnection() { X1 = 406, Y1 = 224, X2 = 230, Y2 = 350 },
				new MapConnection() { X1 = 406, Y1 = 224, X2 = 687, Y2 = 150 },
				new MapConnection() { X1 = 406, Y1 = 224, X2 = 326, Y2 = 418 },
				new MapConnection() { X1 = 406, Y1 = 224, X2 = 340, Y2 = 130 },
				new MapConnection() { X1 = 720, Y1 = 440, X2 = 660, Y2 = 505 },
				new MapConnection() { X1 = 720, Y1 = 440, X2 = 406, Y2 = 224 },
				new MapConnection() { X1 = 660, Y1 = 505, X2 = 720, Y2 = 440 },
			},
			new List<MapConnection>()
			{
				new MapConnection() { X1 = 195, Y1 = 475, X2 = 176, Y2 = 520 },
				new MapConnection() { X1 = 195, Y1 = 475, X2 = 200, Y2 = 420 },
				new MapConnection() { X1 = 200, Y1 = 420, X2 = 240, Y2 = 450 },
				new MapConnection() { X1 = 200, Y1 = 420, X2 = 235, Y2 = 380 },
				new MapConnection() { X1 = 235, Y1 = 380, X2 = 180, Y2 = 345 },
				new MapConnection() { X1 = 180, Y1 = 345, X2 = 176, Y2 = 265 },
				new MapConnection() { X1 = 176, Y1 = 265, X2 = 210, Y2 = 200 },
				new MapConnection() { X1 = 210, Y1 = 200, X2 = 270, Y2 = 200 },
				new MapConnection() { X1 = 270, Y1 = 200, X2 = 280, Y2 = 150 },
				new MapConnection() { X1 = 280, Y1 = 150, X2 = 370, Y2 = 180 },
				new MapConnection() { X1 = 370, Y1 = 180, X2 = 350, Y2 = 130 },
				new MapConnection() { X1 = 370, Y1 = 180, X2 = 450, Y2 = 200 },
				new MapConnection() { X1 = 450, Y1 = 200, X2 = 460, Y2 = 250 },
				new MapConnection() { X1 = 460, Y1 = 250, X2 = 540, Y2 = 250 },
				new MapConnection() { X1 = 540, Y1 = 250, X2 = 714, Y2 = 197 },
			},
			new List<MapConnection>()
			{
				new MapConnection() { X1 = 675, Y1 = 218, X2 = 617, Y2 = 234 },
				new MapConnection() { X1 = 617, Y1 = 234, X2 = 587, Y2 = 322 },
				new MapConnection() { X1 = 587, Y1 = 322, X2 = 663, Y2 = 402 },
				new MapConnection() { X1 = 587, Y1 = 322, X2 = 499, Y2 = 235 },
				new MapConnection() { X1 = 587, Y1 = 322, X2 = 485, Y2 = 458 },
				new MapConnection() { X1 = 663, Y1 = 402, X2 = 739, Y2 = 414 },
				new MapConnection() { X1 = 499, Y1 = 235, X2 = 435, Y2 = 200 },
				new MapConnection() { X1 = 499, Y1 = 235, X2 = 487, Y2 = 347 },
				new MapConnection() { X1 = 487, Y1 = 347, X2 = 485, Y2 = 458 },
				new MapConnection() { X1 = 485, Y1 = 458, X2 = 170, Y2 = 307 },
				new MapConnection() { X1 = 170, Y1 = 307, X2 = 96, Y2 = 344 },
				new MapConnection() { X1 = 170, Y1 = 307, X2 = 206, Y2 = 203 },
				new MapConnection() { X1 = 206, Y1 = 203, X2 = 155, Y2 = 161 },
				new MapConnection() { X1 = 155, Y1 = 161, X2 = 96, Y2 = 139 },
			},
			new List<MapConnection>()
			{
				new MapConnection() { X1 = 682, Y1 = 429, X2 = 461, Y2 = 369 },
				new MapConnection() { X1 = 461, Y1 = 369, X2 = 461, Y2 = 290 },
				new MapConnection() { X1 = 461, Y1 = 290, X2 = 286, Y2 = 307 },
				new MapConnection() { X1 = 461, Y1 = 290, X2 = 565, Y2 = 270 },
				new MapConnection() { X1 = 286, Y1 = 307, X2 = 291, Y2 = 233 },
				new MapConnection() { X1 = 291, Y1 = 233, X2 = 214, Y2 = 233 },
				new MapConnection() { X1 = 291, Y1 = 233, X2 = 295, Y2 = 178 },
				new MapConnection() { X1 = 295, Y1 = 178, X2 = 188, Y2 = 169 },
				new MapConnection() { X1 = 295, Y1 = 178, X2 = 405, Y2 = 195 },
				new MapConnection() { X1 = 565, Y1 = 270, X2 = 662, Y2 = 252 },
				new MapConnection() { X1 = 662, Y1 = 252, X2 = 781, Y2 = 164 },
				new MapConnection() { X1 = 781, Y1 = 164, X2 = 540, Y2 = 92 },
				new MapConnection() { X1 = 478, Y1 = 140, X2 = 405, Y2 = 195 },
				new MapConnection() { X1 = 540, Y1 = 92, X2 = 478, Y2 = 140 },
			},
			new List<MapConnection>()
			{
				new MapConnection() { X1 = 364, Y1 = 506, X2 = 252, Y2 = 425 },
				new MapConnection() { X1 = 252, Y1 = 425, X2 = 460, Y2 = 326 },
				new MapConnection() { X1 = 460, Y1 = 326, X2 = 680, Y2 = 508 },
				new MapConnection() { X1 = 680, Y1 = 508, X2 = 805, Y2 = 334 },
				new MapConnection() { X1 = 680, Y1 = 508, X2 = 640, Y2 = 285 },
				new MapConnection() { X1 = 640, Y1 = 285, X2 = 590, Y2 = 193 },
				new MapConnection() { X1 = 640, Y1 = 285, X2 = 491, Y2 = 191 },
				new MapConnection() { X1 = 491, Y1 = 191, X2 = 376, Y2 = 161 },
				new MapConnection() { X1 = 376, Y1 = 161, X2 = 396, Y2 = 113 },
				new MapConnection() { X1 = 376, Y1 = 161, X2 = 163, Y2 = 137 },
				new MapConnection() { X1 = 163, Y1 = 137, X2 = 83, Y2 = 195 },
			},
			new List<MapConnection>()
			{
				new MapConnection() { X1 = 262, Y1 = 60, X2 = 340, Y2 = 130 },
				new MapConnection() { X1 = 340, Y1 = 130, X2 = 406, Y2 = 224 },
				new MapConnection() { X1 = 406, Y1 = 224, X2 = 720, Y2 = 440 },
				new MapConnection() { X1 = 406, Y1 = 224, X2 = 640, Y2 = 223 },
				new MapConnection() { X1 = 406, Y1 = 224, X2 = 230, Y2 = 350 },
				new MapConnection() { X1 = 406, Y1 = 224, X2 = 326, Y2 = 418 },
				new MapConnection() { X1 = 406, Y1 = 224, X2 = 687, Y2 = 150 },
				new MapConnection() { X1 = 720, Y1 = 440, X2 = 660, Y2 = 505 },
				new MapConnection() { X1 = 640, Y1 = 223, X2 = 750, Y2 = 215 },
			},
		};
		public static List<MapPin>[] fMapPins = new List<MapPin>[]
		{
			new List<MapPin>()
			{
				new MapPin()
				{
					X = 264, Y = 405, Name = "Lioneye's Watch", IsTown = true, IsWaypoint = true,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "1_1_town", Level = 13 }}
				},
				new MapPin()
				{
					X = 244, Y = 486, Name = "The Twilight Strand", IsTown = false, IsWaypoint = false,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "1_1_1", Level = 1 }}
				},
				new MapPin()
				{
					X = 285, Y = 346, Name = "The Coast", IsTown = false, IsWaypoint = true,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "1_1_2", Level = 2 }}
				},
				new MapPin()
				{
					X = 325, Y = 375, Name = "The Tidal Island", IsTown = false, IsWaypoint = false,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "1_1_2a", Level = 3 }}
				},
				new MapPin()
				{
					X = 314, Y = 300, Name = "The Mud Flats", IsTown = false, IsWaypoint = false,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "1_1_3", Level = 4 }}
				},
				new MapPin()
				{
					X = 283, Y = 231, Name = "The Fetid Pool", IsTown = false, IsWaypoint = false,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "1_1_3a", Level = 5 }}
				},
				new MapPin()
				{
					X = 426, Y = 279, Name = "The Flooded Depths", IsTown = false, IsWaypoint = false,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "1_1_4_0", Level = 6 }}
				},
				new MapPin()
				{
					X = 371, Y = 247, Name = "The Submerged Passage", IsTown = false, IsWaypoint = true,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "1_1_4_1", Level = 5 }}
				},
				new MapPin()
				{
					X = 419, Y = 211, Name = "The Ledge", IsTown = false, IsWaypoint = true,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "1_1_5", Level = 6 }}
				},
				new MapPin()
				{
					X = 324, Y = 161, Name = "The Climb", IsTown = false, IsWaypoint = true,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "1_1_6", Level = 7 }}
				},
				new MapPin()
				{
					X = 305, Y = 68, Name = "The Prison", IsTown = false, IsWaypoint = true,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "1_1_7_1", Level = 8 }, new MapWorldArea(){ Code = "1_1_7_2", Level = 9 }}
				},
				new MapPin()
				{
					X = 385, Y = 68, Name = "Prisoner's Gate", IsTown = false, IsWaypoint = true,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "1_1_8", Level = 10 }}
				},
				new MapPin()
				{
					X = 480, Y = 158, Name = "The Ship Graveyard", IsTown = false, IsWaypoint = true,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "1_1_9", Level = 11 }}
				},
				new MapPin()
				{
					X = 470, Y = 107, Name = "The Ship Graveyard Cave", IsTown = false, IsWaypoint = false,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "1_1_9a", Level = 12 }}
				},
				new MapPin()
				{
					X = 626, Y = 117, Name = "Merveil's Caverns", IsTown = false, IsWaypoint = true,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "1_1_11_1", Level = 12 }, new MapWorldArea(){ Code = "1_1_11_2", Level = 13 }}
				},
			},
			new List<MapPin>()
			{
				new MapPin()
				{
					X = 528, Y = 313, Name = "The Forest Encampment", IsTown = true, IsWaypoint = true,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "1_2_town", Level = 23 }}
				},
				new MapPin()
				{
					X = 574, Y = 400, Name = "The Southern Forest", IsTown = false, IsWaypoint = true,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "1_2_1", Level = 13 }}
				},
				new MapPin()
				{
					X = 574, Y = 267, Name = "The Old Fields", IsTown = false, IsWaypoint = false,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "1_2_2", Level = 14 }}
				},
				new MapPin()
				{
					X = 530, Y = 218, Name = "The Den", IsTown = false, IsWaypoint = false,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "1_2_2a", Level = 15 }}
				},
				new MapPin()
				{
					X = 615, Y = 196, Name = "The Crossroads", IsTown = false, IsWaypoint = true,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "1_2_3", Level = 15 }}
				},
				new MapPin()
				{
					X = 745, Y = 275, Name = "The Crypt", IsTown = false, IsWaypoint = true,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "1_2_5_1", Level = 17 }, new MapWorldArea(){ Code = "1_2_5_2", Level = 18 }}
				},
				new MapPin()
				{
					X = 540, Y = 122, Name = "The Chamber of Sins", IsTown = false, IsWaypoint = true,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "1_2_6_1", Level = 15 }, new MapWorldArea(){ Code = "1_2_6_2", Level = 16 }}
				},
				new MapPin()
				{
					X = 641, Y = 121, Name = "The Broken Bridge", IsTown = false, IsWaypoint = true,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "1_2_4", Level = 16 }}
				},
				new MapPin()
				{
					X = 411, Y = 340, Name = "The Riverways", IsTown = false, IsWaypoint = true,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "1_2_7", Level = 15 }}
				},
				new MapPin()
				{
					X = 259, Y = 183, Name = "The Northern Forest", IsTown = false, IsWaypoint = true,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "1_2_8", Level = 21 }}
				},
				new MapPin()
				{
					X = 221, Y = 288, Name = "The Western Forest", IsTown = false, IsWaypoint = true,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "1_2_9", Level = 17 }}
				},
				new MapPin()
				{
					X = 248, Y = 334, Name = "The Weaver's Chambers", IsTown = false, IsWaypoint = false,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "1_2_10", Level = 18 }}
				},
				new MapPin()
				{
					X = 318, Y = 220, Name = "The Vaal Ruins", IsTown = false, IsWaypoint = false,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "1_2_11", Level = 20 }}
				},
				new MapPin()
				{
					X = 355, Y = 270, Name = "The Wetlands", IsTown = false, IsWaypoint = true,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "1_2_12", Level = 19 }}
				},
				new MapPin()
				{
					X = 196, Y = 215, Name = "The Dread Thicket", IsTown = false, IsWaypoint = false,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "1_2_13", Level = 21 }}
				},
				new MapPin()
				{
					X = 144, Y = 91, Name = "The Caverns", IsTown = false, IsWaypoint = true,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "1_2_14_2", Level = 22 }, new MapWorldArea(){ Code = "1_2_14_3", Level = 23 }}
				},
				new MapPin()
				{
					X = 680, Y = 265, Name = "The Fellshrine Ruins", IsTown = false, IsWaypoint = false,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "1_2_15", Level = 16 }}
				},
			},
			new List<MapPin>()
			{
				new MapPin()
				{
					X = 461, Y = 369, Name = "The Sarn Encampment", IsTown = true, IsWaypoint = true,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "1_3_town", Level = 33 }}
				},
				new MapPin()
				{
					X = 662, Y = 381, Name = "The City of Sarn", IsTown = false, IsWaypoint = true,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "1_3_1", Level = 23 }}
				},
				new MapPin()
				{
					X = 652, Y = 309, Name = "The Slums", IsTown = false, IsWaypoint = false,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "1_3_2", Level = 24 }}
				},
				new MapPin()
				{
					X = 714, Y = 309, Name = "The Crematorium", IsTown = false, IsWaypoint = true,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "1_3_3_1", Level = 25 }}
				},
				new MapPin()
				{
					X = 589, Y = 185, Name = "The Marketplace", IsTown = false, IsWaypoint = true,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "1_3_5", Level = 26 }}
				},
				new MapPin()
				{
					X = 652, Y = 168, Name = "The Catacombs", IsTown = false, IsWaypoint = false,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "1_3_6", Level = 27 }}
				},
				new MapPin()
				{
					X = 478, Y = 140, Name = "The Battlefront", IsTown = false, IsWaypoint = true,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "1_3_7", Level = 27 }}
				},
				new MapPin()
				{
					X = 556, Y = 97, Name = "The Solaris Temple Level 1", IsTown = false, IsWaypoint = true,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "1_3_8_1", Level = 27 }}
				},
				new MapPin()
				{
					X = 503, Y = 61, Name = "The Solaris Temple Level 2", IsTown = false, IsWaypoint = true,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "1_3_8_2", Level = 28 }}
				},
				new MapPin()
				{
					X = 394, Y = 118, Name = "The Docks", IsTown = false, IsWaypoint = true,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "1_3_9", Level = 29 }}
				},
				new MapPin()
				{
					X = 616, Y = 252, Name = "The Sewers", IsTown = false, IsWaypoint = true,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "1_3_10_1", Level = 26 }}
				},
				new MapPin()
				{
					X = 295, Y = 178, Name = "The Ebony Barracks", IsTown = false, IsWaypoint = true,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "1_3_13", Level = 29 }}
				},
				new MapPin()
				{
					X = 188, Y = 169, Name = "The Lunaris Temple", IsTown = false, IsWaypoint = true,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "1_3_14_1", Level = 29 }, new MapWorldArea(){ Code = "1_3_14_2", Level = 30 }}
				},
				new MapPin()
				{
					X = 262, Y = 129, Name = "The Imperial Gardens", IsTown = false, IsWaypoint = true,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "1_3_15", Level = 30 }}
				},
				new MapPin()
				{
					X = 217, Y = 98, Name = "The Library", IsTown = false, IsWaypoint = true,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "1_3_17_1", Level = 30 }, new MapWorldArea(){ Code = "1_3_17_2", Level = 31 }}
				},
				new MapPin()
				{
					X = 285, Y = 76, Name = "The Sceptre of God", IsTown = false, IsWaypoint = true,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "1_3_18_1", Level = 32 }, new MapWorldArea(){ Code = "1_3_18_2", Level = 33 }}
				},
			},
			new List<MapPin>()
			{
				new MapPin()
				{
					X = 610, Y = 370, Name = "Highgate", IsTown = true, IsWaypoint = true,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "1_4_town", Level = 40 }}
				},
				new MapPin()
				{
					X = 749, Y = 477, Name = "The Aqueduct", IsTown = false, IsWaypoint = true,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "1_4_1", Level = 33 }}
				},
				new MapPin()
				{
					X = 315, Y = 518, Name = "The Dried Lake", IsTown = false, IsWaypoint = false,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "1_4_2", Level = 34 }}
				},
				new MapPin()
				{
					X = 555, Y = 275, Name = "The Mines", IsTown = false, IsWaypoint = false,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "1_4_3_1", Level = 34 }, new MapWorldArea(){ Code = "1_4_3_2", Level = 35 }}
				},
				new MapPin()
				{
					X = 474, Y = 236, Name = "The Crystal Veins", IsTown = false, IsWaypoint = true,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "1_4_3_3", Level = 36 }}
				},
				new MapPin()
				{
					X = 292, Y = 344, Name = "Kaom's Dream", IsTown = false, IsWaypoint = false,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "1_4_4_1", Level = 37 }}
				},
				new MapPin()
				{
					X = 196, Y = 289, Name = "Kaom's Stronghold", IsTown = false, IsWaypoint = true,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "1_4_4_3", Level = 38 }}
				},
				new MapPin()
				{
					X = 534, Y = 144, Name = "Daresso's Dream", IsTown = false, IsWaypoint = false,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "1_4_5_1", Level = 37 }}
				},
				new MapPin()
				{
					X = 464, Y = 90, Name = "The Grand Arena", IsTown = false, IsWaypoint = true,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "1_4_5_2", Level = 38 }}
				},
				new MapPin()
				{
					X = 372, Y = 194, Name = "The Belly of the Beast", IsTown = false, IsWaypoint = false,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "1_4_6_1", Level = 38 }, new MapWorldArea(){ Code = "1_4_6_2", Level = 39 }}
				},
				new MapPin()
				{
					X = 280, Y = 144, Name = "The Harvest", IsTown = false, IsWaypoint = true,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "1_4_6_3", Level = 40 }}
				},
				new MapPin()
				{
					X = 729, Y = 154, Name = "The Ascent", IsTown = false, IsWaypoint = false,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "1_4_7", Level = 40 }}
				},
			},
			new List<MapPin>()
			{
				new MapPin()
				{
					X = 164, Y = 285, Name = "Overseer's Tower", IsTown = true, IsWaypoint = true,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "1_5_town", Level = 45 }}
				},
				new MapPin()
				{
					X = 75, Y = 298, Name = "The Slave Pens", IsTown = false, IsWaypoint = true,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "1_5_1", Level = 41 }}
				},
				new MapPin()
				{
					X = 230, Y = 350, Name = "The Control Blocks", IsTown = false, IsWaypoint = false,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "1_5_2", Level = 41 }}
				},
				new MapPin()
				{
					X = 406, Y = 224, Name = "Oriath Square", IsTown = false, IsWaypoint = true,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "1_5_3", Level = 42 }}
				},
				new MapPin()
				{
					X = 406, Y = 224, Name = "The Ruined Square", IsTown = false, IsWaypoint = true,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "1_5_3b", Level = 44 }}
				},
				new MapPin()
				{
					X = 720, Y = 440, Name = "The Templar Courts", IsTown = false, IsWaypoint = true,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "1_5_4", Level = 42 }}
				},
				new MapPin()
				{
					X = 720, Y = 440, Name = "The Torched Courts", IsTown = false, IsWaypoint = false,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "1_5_4b", Level = 44 }}
				},
				new MapPin()
				{
					X = 660, Y = 505, Name = "The Chamber of Innocence", IsTown = false, IsWaypoint = true,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "1_5_5", Level = 43 }}
				},
				new MapPin()
				{
					X = 687, Y = 150, Name = "The Ossuary", IsTown = false, IsWaypoint = false,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "1_5_6", Level = 44 }}
				},
				new MapPin()
				{
					X = 326, Y = 418, Name = "The Reliquary", IsTown = false, IsWaypoint = true,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "1_5_7", Level = 44 }}
				},
				new MapPin()
				{
					X = 340, Y = 130, Name = "The Cathedral Rooftop", IsTown = false, IsWaypoint = true,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "1_5_8", Level = 45 }}
				},
			},
			new List<MapPin>()
			{
				new MapPin()
				{
					X = 195, Y = 475, Name = "Lioneye's Watch", IsTown = true, IsWaypoint = true,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "2_6_town", Level = 50 }}
				},
				new MapPin()
				{
					X = 176, Y = 520, Name = "The Twilight Strand", IsTown = false, IsWaypoint = false,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "2_6_1", Level = 45 }}
				},
				new MapPin()
				{
					X = 200, Y = 420, Name = "The Coast", IsTown = false, IsWaypoint = true,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "2_6_2", Level = 45 }}
				},
				new MapPin()
				{
					X = 240, Y = 450, Name = "The Tidal Island", IsTown = false, IsWaypoint = false,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "2_6_3", Level = 45 }}
				},
				new MapPin()
				{
					X = 235, Y = 380, Name = "The Mud Flats", IsTown = false, IsWaypoint = false,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "2_6_4", Level = 46 }}
				},
				new MapPin()
				{
					X = 180, Y = 345, Name = "The Karui Fortress", IsTown = false, IsWaypoint = false,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "2_6_5", Level = 46 }}
				},
				new MapPin()
				{
					X = 176, Y = 265, Name = "The Ridge", IsTown = false, IsWaypoint = true,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "2_6_6", Level = 46 }}
				},
				new MapPin()
				{
					X = 210, Y = 200, Name = "The Prison", IsTown = false, IsWaypoint = true,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "2_6_7_1", Level = 47 }, new MapWorldArea(){ Code = "2_6_7_2", Level = 47 }}
				},
				new MapPin()
				{
					X = 270, Y = 200, Name = "Prisoner's Gate", IsTown = false, IsWaypoint = true,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "2_6_8", Level = 47 }}
				},
				new MapPin()
				{
					X = 280, Y = 150, Name = "The Western Forest", IsTown = false, IsWaypoint = true,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "2_6_9", Level = 48 }}
				},
				new MapPin()
				{
					X = 370, Y = 180, Name = "The Riverways", IsTown = false, IsWaypoint = true,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "2_6_10", Level = 48 }}
				},
				new MapPin()
				{
					X = 350, Y = 130, Name = "The Wetlands", IsTown = false, IsWaypoint = false,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "2_6_11", Level = 48 }}
				},
				new MapPin()
				{
					X = 450, Y = 200, Name = "The Southern Forest", IsTown = false, IsWaypoint = true,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "2_6_12", Level = 49 }}
				},
				new MapPin()
				{
					X = 460, Y = 250, Name = "The Cavern of Anger", IsTown = false, IsWaypoint = false,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "2_6_13", Level = 49 }}
				},
				new MapPin()
				{
					X = 540, Y = 250, Name = "The Beacon", IsTown = false, IsWaypoint = true,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "2_6_14", Level = 49 }}
				},
				new MapPin()
				{
					X = 714, Y = 197, Name = "The Brine King's Reef", IsTown = false, IsWaypoint = true,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "2_6_15", Level = 50 }}
				},
			},
			new List<MapPin>()
			{
				new MapPin()
				{
					X = 675, Y = 218, Name = "The Bridge Encampment", IsTown = true, IsWaypoint = true,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "2_7_town", Level = 55 }}
				},
				new MapPin()
				{
					X = 617, Y = 234, Name = "The Broken Bridge", IsTown = false, IsWaypoint = false,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "2_7_1", Level = 50 }}
				},
				new MapPin()
				{
					X = 587, Y = 322, Name = "The Crossroads", IsTown = false, IsWaypoint = true,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "2_7_2", Level = 51 }}
				},
				new MapPin()
				{
					X = 663, Y = 402, Name = "The Fellshrine Ruins", IsTown = false, IsWaypoint = false,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "2_7_3", Level = 51 }}
				},
				new MapPin()
				{
					X = 739, Y = 414, Name = "The Crypt", IsTown = false, IsWaypoint = true,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "2_7_4", Level = 51 }}
				},
				new MapPin()
				{
					X = 499, Y = 235, Name = "The Chamber of Sins", IsTown = false, IsWaypoint = true,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "2_7_5_1", Level = 52 }, new MapWorldArea(){ Code = "2_7_5_2", Level = 52 }}
				},
				new MapPin()
				{
					X = 435, Y = 200, Name = "Maligaro's Sanctum", IsTown = false, IsWaypoint = false,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "2_7_5_map", Level = 52 }}
				},
				new MapPin()
				{
					X = 487, Y = 347, Name = "The Den", IsTown = false, IsWaypoint = true,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "2_7_6", Level = 53 }}
				},
				new MapPin()
				{
					X = 485, Y = 458, Name = "The Ashen Fields", IsTown = false, IsWaypoint = true,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "2_7_7", Level = 53 }}
				},
				new MapPin()
				{
					X = 170, Y = 307, Name = "The Northern Forest", IsTown = false, IsWaypoint = true,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "2_7_8", Level = 53 }}
				},
				new MapPin()
				{
					X = 96, Y = 344, Name = "The Dread Thicket", IsTown = false, IsWaypoint = false,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "2_7_9", Level = 53 }}
				},
				new MapPin()
				{
					X = 206, Y = 203, Name = "The Causeway", IsTown = false, IsWaypoint = true,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "2_7_10", Level = 54 }}
				},
				new MapPin()
				{
					X = 155, Y = 161, Name = "The Vaal City", IsTown = false, IsWaypoint = true,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "2_7_11", Level = 54 }}
				},
				new MapPin()
				{
					X = 96, Y = 139, Name = "The Temple of Decay", IsTown = false, IsWaypoint = false,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "2_7_12_1", Level = 54 }, new MapWorldArea(){ Code = "2_7_12_2", Level = 55 }}
				},
			},
			new List<MapPin>()
			{
				new MapPin()
				{
					X = 682, Y = 429, Name = "The Sarn Ramparts", IsTown = false, IsWaypoint = true,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "2_8_1", Level = 55 }}
				},
				new MapPin()
				{
					X = 461, Y = 369, Name = "The Sarn Encampment", IsTown = true, IsWaypoint = true,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "2_8_town", Level = 60 }}
				},
				new MapPin()
				{
					X = 461, Y = 290, Name = "The Toxic Conduits", IsTown = false, IsWaypoint = true,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "2_8_2_1", Level = 56 }, new MapWorldArea(){ Code = "2_8_2_2", Level = 56 }}
				},
				new MapPin()
				{
					X = 286, Y = 307, Name = "The Grand Promenade", IsTown = false, IsWaypoint = false,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "2_8_3", Level = 56 }}
				},
				new MapPin()
				{
					X = 214, Y = 233, Name = "The High Gardens", IsTown = false, IsWaypoint = false,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "2_8_4", Level = 58 }}
				},
				new MapPin()
				{
					X = 291, Y = 233, Name = "The Bath House", IsTown = false, IsWaypoint = true,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "2_8_5", Level = 57 }}
				},
				new MapPin()
				{
					X = 295, Y = 178, Name = "The Lunaris Concourse", IsTown = false, IsWaypoint = true,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "2_8_6", Level = 58 }}
				},
				new MapPin()
				{
					X = 188, Y = 169, Name = "The Lunaris Temple", IsTown = false, IsWaypoint = true,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "2_8_7_1_", Level = 59 }, new MapWorldArea(){ Code = "2_8_7_2", Level = 59 }}
				},
				new MapPin()
				{
					X = 565, Y = 270, Name = "The Quay", IsTown = false, IsWaypoint = false,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "2_8_8", Level = 57 }}
				},
				new MapPin()
				{
					X = 662, Y = 252, Name = "The Grain Gate", IsTown = false, IsWaypoint = true,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "2_8_9", Level = 57 }}
				},
				new MapPin()
				{
					X = 781, Y = 164, Name = "The Imperial Fields", IsTown = false, IsWaypoint = true,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "2_8_10", Level = 58 }}
				},
				new MapPin()
				{
					X = 478, Y = 140, Name = "The Solaris Concourse", IsTown = false, IsWaypoint = true,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "2_8_11", Level = 58 }}
				},
				new MapPin()
				{
					X = 540, Y = 92, Name = "The Solaris Temple", IsTown = false, IsWaypoint = true,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "2_8_12_1", Level = 59 }, new MapWorldArea(){ Code = "2_8_12_2", Level = 59 }}
				},
				new MapPin()
				{
					X = 405, Y = 195, Name = "The Harbour Bridge", IsTown = false, IsWaypoint = false,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "2_8_13", Level = 60 }}
				},
			},
			new List<MapPin>()
			{
				new MapPin()
				{
					X = 364, Y = 506, Name = "The Blood Aqueduct", IsTown = false, IsWaypoint = true,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "2_9_1", Level = 61 }}
				},
				new MapPin()
				{
					X = 252, Y = 425, Name = "Highgate", IsTown = true, IsWaypoint = true,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "2_9_town", Level = 67 }}
				},
				new MapPin()
				{
					X = 460, Y = 326, Name = "The Descent", IsTown = false, IsWaypoint = false,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "2_9_2", Level = 61 }}
				},
				new MapPin()
				{
					X = 680, Y = 508, Name = "The Vastiri Desert", IsTown = false, IsWaypoint = true,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "2_9_3", Level = 61 }}
				},
				new MapPin()
				{
					X = 805, Y = 334, Name = "The Oasis", IsTown = false, IsWaypoint = false,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "2_9_4", Level = 61 }}
				},
				new MapPin()
				{
					X = 640, Y = 285, Name = "The Foothills", IsTown = false, IsWaypoint = true,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "2_9_5", Level = 62 }}
				},
				new MapPin()
				{
					X = 590, Y = 193, Name = "The Boiling Lake", IsTown = false, IsWaypoint = false,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "2_9_6", Level = 62 }}
				},
				new MapPin()
				{
					X = 491, Y = 191, Name = "The Tunnel", IsTown = false, IsWaypoint = true,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "2_9_7", Level = 62 }}
				},
				new MapPin()
				{
					X = 376, Y = 161, Name = "The Quarry", IsTown = false, IsWaypoint = true,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "2_9_8", Level = 63 }}
				},
				new MapPin()
				{
					X = 396, Y = 113, Name = "The Refinery", IsTown = false, IsWaypoint = false,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "2_9_9", Level = 63 }}
				},
				new MapPin()
				{
					X = 163, Y = 137, Name = "The Belly of the Beast", IsTown = false, IsWaypoint = false,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "2_9_10_1", Level = 63 }}
				},
				new MapPin()
				{
					X = 83, Y = 195, Name = "The Rotting Core", IsTown = false, IsWaypoint = false,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "2_9_10_2", Level = 64 }}
				},
			},
			new List<MapPin>()
			{
				new MapPin()
				{
					X = 262, Y = 60, Name = "Oriath Docks", IsTown = true, IsWaypoint = true,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "2_10_town", Level = 69 }}
				},
				new MapPin()
				{
					X = 340, Y = 130, Name = "The Cathedral Rooftop", IsTown = false, IsWaypoint = false,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "2_10_1", Level = 64 }}
				},
				new MapPin()
				{
					X = 406, Y = 224, Name = "The Ravaged Square", IsTown = false, IsWaypoint = true,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "2_10_2", Level = 64 }}
				},
				new MapPin()
				{
					X = 720, Y = 440, Name = "The Torched Courts", IsTown = false, IsWaypoint = false,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "2_10_3", Level = 65 }}
				},
				new MapPin()
				{
					X = 660, Y = 505, Name = "The Desecrated Chambers", IsTown = false, IsWaypoint = true,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "2_10_4", Level = 65 }}
				},
				new MapPin()
				{
					X = 640, Y = 223, Name = "The Canals", IsTown = false, IsWaypoint = false,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "2_10_5", Level = 66 }}
				},
				new MapPin()
				{
					X = 750, Y = 215, Name = "The Feeding Trough", IsTown = false, IsWaypoint = false,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "2_10_6", Level = 67 }}
				},
				new MapPin()
				{
					X = 230, Y = 350, Name = "The Control Blocks", IsTown = false, IsWaypoint = true,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "2_10_7", Level = 66 }}
				},
				new MapPin()
				{
					X = 326, Y = 418, Name = "The Reliquary", IsTown = false, IsWaypoint = true,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "2_10_8", Level = 67 }}
				},
				new MapPin()
				{
					X = 687, Y = 150, Name = "The Ossuary", IsTown = false, IsWaypoint = false,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "2_10_9", Level = 67 }}
				},
			},
			new List<MapPin>()
			{
				new MapPin()
				{
					X = 781, Y = 354, Name = "Karui Shores", IsTown = true, IsWaypoint = true,
					Areas = new MapWorldArea[]{new MapWorldArea(){ Code = "2_11_endgame_town", Level = 69 }}
				},
			},
		};
		public static Dictionary<int, int> fExperienceForZoneLevel = new Dictionary<int, int>()
		{
			{1, 20},
			{2, 20},
			{3, 25},
			{4, 38},
			{5, 51},
			{6, 67},
			{7, 88},
			{8, 113},
			{9, 141},
			{10, 173},
			{11, 211},
			{12, 250},
			{13, 297},
			{14, 347},
			{15, 402},
			{16, 461},
			{17, 526},
			{18, 596},
			{19, 668},
			{20, 748},
			{21, 831},
			{22, 921},
			{23, 1013},
			{24, 1113},
			{25, 1216},
			{26, 1325},
			{27, 1437},
			{28, 1560},
			{29, 1685},
			{30, 1812},
			{31, 1950},
			{32, 2089},
			{33, 2235},
			{34, 2386},
			{35, 2543},
			{36, 2705},
			{37, 2873},
			{38, 3045},
			{39, 3227},
			{40, 3407},
			{41, 3597},
			{42, 3796},
			{43, 3993},
			{44, 4203},
			{45, 4415},
			{46, 4634},
			{47, 4854},
			{48, 5086},
			{49, 5318},
			{50, 5561},
			{51, 5808},
			{52, 6064},
			{53, 6324},
			{54, 6585},
			{55, 6859},
			{56, 7134},
			{57, 7413},
			{58, 7703},
			{59, 7996},
			{60, 8265},
			{61, 8525},
			{62, 8781},
			{63, 9032},
			{64, 9283},
			{65, 9532},
			{66, 9773},
			{67, 10014},
			{68, 10255},
			{69, 10487},
			{70, 10720},
			{71, 10949},
			{72, 11170},
			{73, 11388},
			{74, 11601},
			{75, 11804},
			{76, 12004},
			{77, 12192},
			{78, 12377},
			{79, 12549},
			{80, 12712},
			{81, 12863},
			{82, 13006},
			{83, 13132},
			{84, 13250},
			{85, 13352},
			{86, 13440},
			{87, 13512},
			{88, 13569},
			{89, 13609},
			{90, 13633},
			{91, 13639},
			{92, 13627},
			{93, 13598},
			{94, 13549},
			{95, 13483},
			{96, 13396},
			{97, 13293},
			{98, 13170},
			{99, 13029},
			{100, 0},
		};
	}
}
